services:
  exchangeDB:
    container_name: exchangeDB
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - exchangeDB
    command: >
      sh -c "python exchanging/manage.py migrate &&
             python exchanging/manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: