# Generated by Django 5.2.1 on 2025-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(default='Новое', max_length=64),
            preserve_default=False,
        ),
    ]
